topic:
  name: ordertopic
  partitions-num: 3
  replication-factor: 1
server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      # Schema Registry Connection parameter
      schema.registry.url: http://localhost:8081
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic:
logging:
      level:
        root: info